### ISSUE TITLE
Extra text in [Collection] chooser

### ISSUE THREAD

**Issue by annihat** [fvasco/pinpoi#23] opened 2018-05-19 11:18 UTC
From the main screen, [Collection] button produces text extra to the name I edited in #22

**Comment by annihat** [comment] 2018-05-19 11:22
This extra text is from the KMZ file http://download.bournemouth.ac.uk/apsci/srp/Seeing-Beneath-Stonehenge.kmz

**Comment by fvasco** [comment] 2018-05-20 06:12
@annihat I cannot reproduce this issue, can you expose me a use-case or provides some screenshots?

**Comment by fvasco** [comment] 2018-05-28 16:39
@annihat any news? Should I close this issue?

**Closed as completed** 2018-05-29 19:37 UTC
Labels: help wanted

**Comment by annihat** [comment] 2021-04-16 10:24
Hi, really sorry, I didn't see notifications for this so didn't come back. 
I can't remember what was going wrong & it works now with the downloaded file though there is a certificate problem (probably a missing root certificate) on my new phone so I can't test the online offering
